## EJERCICIO SOBRE NUMPY 1 - PAIR PROGRAMMING 1 MODULO 1 SPRINT 1 

En el ejercicio de hoy vamos a empezar a trabajar con NumPy. El objetivo de estos ejericicios es que creeis una serie de arrays, y hagáis una serie de operaciones matemáticas con ellos.

1. Cread tres arrays: de una, dos y tres dimensiones.
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos. NOTAS:
- El array de 2 dimensiones debe ser de 2 filas y 3 columnas
- El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [2]:
import numpy as np

In [3]:
array1 = np.random.rand(2,3)

In [4]:
array1

array([[0.7700108 , 0.41397631, 0.60469503],
       [0.2993228 , 0.65855382, 0.08628654]])

In [5]:
array2 = np.random.random_sample((2,3,5))

In [6]:
array2

array([[[0.91525254, 0.70214189, 0.64596337, 0.53864308, 0.5546577 ],
        [0.37074891, 0.47679989, 0.02939025, 0.00706987, 0.98326051],
        [0.00237892, 0.83068412, 0.96677374, 0.72669628, 0.18106743]],

       [[0.46479146, 0.49321353, 0.37699753, 0.48849823, 0.98849818],
        [0.92249343, 0.93316856, 0.99439675, 0.18945894, 0.55905946],
        [0.91556981, 0.37021401, 0.5707463 , 0.35068374, 0.8260727 ]]])

In [7]:
array2.ndim

3

2. Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [ ]:
#propiedades: 
# -size
# -shape
# -ndim

In [10]:
def forma(array):
  return array.shape

In [12]:
def tamaño(array):
  return array.size

In [13]:
def dimension(array):
  return array.ndim

In [34]:
#En una sola función:
def propiedades (array):
    print(f"Este array tiene una forma {array.shape}")
    print(f"Este array tiene un tamaño {array.size}")
    print(f"Este array tiene una dimensión {array.ndim}")

In [35]:
propiedades(array2)

Este array tiene una forma (2, 3, 5)
Este array tiene un tamaño 30
Este array tiene una dimensión 3


3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [16]:
matriz_identidad = np.identity(3)
matriz_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [17]:
#matriz de 3 dimensiones (con 1s) == matriz de 3 dimensiones
#palabra clave IGUAL A
matriz_copia = np.ones_like(array2)

In [18]:
matriz_copia

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

5. Es el momento de hacer algunas operaciones entre arrays:
   - ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?
   - En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.
   - Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.
   - Dividid las dos matrices

In [21]:
suma_matrices = np.add(array2,matriz_identidad)
#No es posible realizar la operación porque no tienen la misma dimensión

ValueError: operands could not be broadcast together with shapes (2,3,5) (3,3) 

In [28]:
array_identidad = np.random.rand(2,3,5)
#si hay una diferencia a la hora de utilizar un método random

In [29]:
suma_arrays = np.add(array2,array_identidad)

In [30]:
suma_arrays

array([[[1.9093717 , 0.84118139, 0.76616539, 1.05406503, 1.44218306],
        [0.74171992, 1.09952865, 0.8899973 , 0.41705195, 1.0569773 ],
        [0.22587569, 1.68474291, 1.33498931, 1.65218327, 0.59998109]],

       [[1.4161208 , 1.39332333, 0.41917313, 1.13543584, 1.39867141],
        [1.50354789, 1.86052315, 1.2861255 , 0.27397434, 0.90917608],
        [1.24924613, 1.12660157, 1.33266394, 0.40169638, 0.95682932]]])

In [31]:
multiplicacion_arrays = np.multiply(array_identidad, matriz_identidad)
#no se puede, ya que tienen diferentes dimensiones

ValueError: operands could not be broadcast together with shapes (2,3,5) (3,3) 

In [33]:
division = np.divide (matriz_identidad / array_identidad)
#Tampoco se puede realizar la operación

ValueError: operands could not be broadcast together with shapes (3,3) (2,3,5) 