### Pair Programming NumPy IV


In [2]:
import pandas as pd
import numpy as np

Manos a la obra con la última lección de NumPy. En este caso pondremos en práctica como generar arrays que sigan ciertas distribuciones, así como las operaciones de teoría de conjuntos básicas.

1. ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [21]:

np.random.seed(1)

array1 = np.random.random_sample((2,3))

# usar seed en cada celda para crear cada uno de los arrays

In [22]:
np.random.seed(1)
array2 = np.random.random_sample((2,3))

In [23]:
array1


array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02]])

In [24]:
array2

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02]])

2. Cread los siguientes arrays:

Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.


Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

In [28]:

array3 = np.random.randint(0,10, (2, 3, 5))
print(array3)

valores = np.unique(array3) 
print(valores)

[[[7 7 4 9 0]
  [2 0 7 1 7]
  [9 8 4 0 1]]

 [[9 8 2 3 1]
  [2 7 2 6 0]
  [9 2 6 6 2]]]
[0 1 2 3 4 6 7 8 9]


In [31]:
#Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y 
#número de pruebas igual a 10. Igual que antes, 
#extrae sus valores únicos y guarda los datos en una variable.

array4 = np.random.binomial(10, 0.3, size = (2,3,5))

valores1 = np.unique(array4)
print(valores1)

[0 1 2 3 4 5 6]


In [30]:
array4

array([[[5, 3, 0, 3, 2],
        [3, 5, 2, 5, 3],
        [0, 5, 4, 7, 2]],

       [[1, 5, 4, 1, 4],
        [4, 5, 4, 1, 0],
        [0, 1, 2, 5, 3]]])

3. En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:

Elementos comunes entre los dos arrays

Unión de los dos arrays

¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?

In [32]:


#usamos el método intersect1d añadiendo el parámetro return_indices = True, obteniendo los valores 
#comunes en la intersección de ambos arrays, el parámetro, además, nos devuelve dos arrays más
# dónde el primero corresponde a los índices del array valores y el segundo a los índices del array valores1 

np.intersect1d(valores, valores1, return_indices= True)


(array([0, 1, 2, 3, 4, 6]),
 array([0, 1, 2, 3, 4, 5]),
 array([0, 1, 2, 3, 4, 6]))

In [35]:
#¿Qué elementos están en el array derivado de la distribución uniforme (array3) y no en los únicos 
#de la distribución binomial (array4)? Extrae los valores númericos

# el setdiff1d nos devuelve los valores que se encuentran en array3 y no en array4
 
np.setdiff1d(array3, array4)
 

array([7, 8, 9])

In [33]:

#usamos el método union1d porque devuelve un array ordenado con los elementos resultantes
# de unir los arrays


np.union1d(valores, valores1)



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

4. Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.

Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [37]:
array1 = np.random.randint(1, 100, (80))

array2 = np.random.randint(1, 100, (80))
print( array1)

[ 3 14 42 37 41 19 98 39 64 47 90  3 99 29 79 76 59 43 27 22 59 17 93 38
 12 23  7 97 15 88 76 36 64 33 92 50  1 23 98 71 37 19 28 29 53 95 51 47
  8 86 17 30 12 62 15 31  9 41 49 31 24 67 93 65 13 18 34 11 29 76  6 82
  6 43 87 53 58 57 79 88]


In [39]:
array1 = np.unique(array1)
array2 = np.unique(array2)
print(array1)

[ 1  3  6  7  8  9 11 12 13 14 15 17 18 19 22 23 24 27 28 29 30 31 33 34
 36 37 38 39 41 42 43 47 49 50 51 53 57 58 59 62 64 65 67 71 76 79 82 86
 87 88 90 92 93 95 97 98 99]


In [40]:
array3 = np.setdiff1d (array1, array2)

In [41]:
array3

array([ 1,  7, 12, 14, 15, 18, 23, 24, 27, 30, 33, 36, 37, 42, 50, 53, 57,
       58, 65, 67, 71, 76, 86, 87, 88, 90, 93, 95, 99])

In [43]:
array4 = np.setdiff1d (array2, array1 )

In [44]:
array4

array([ 4,  5, 10, 16, 20, 25, 26, 32, 35, 40, 44, 45, 52, 55, 60, 61, 63,
       68, 69, 70, 73, 75, 77, 78, 80, 81, 83, 89, 96])

In [ ]:
array5 = np.union1d 

In [2]:
len(array1)

NameError: name 'array1' is not defined