## PAIR PROGRAMMING - PANDAS 1

In [2]:
import pandas as pd
import numpy as np

-  Empezamos los ejercicios de pair programming con Pandas. En esta lección hemos aprendido que son las Series y DataFrames y como podemos crearlos en Python.
El objetivo de la clase de hoy será crear unos cuántos DataFrames y Series a través de los siguientes ejercicios:


### 1.¿Qué diferencia hay entre una Serie y un DataFrame?


RESPUESTA --> una Serie es unidimensional y un Dataframe es multidimensional.

### 2. Momento de trabajar con Series. Contestad a las siguientes preguntas:

Crea dos listas:
Una que se llame "valores" que tenga 7 números aleatorios.
Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

In [3]:

valores = [34, 2, 6, 45, 9, 12, 7]

indices = ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']



A partir de estas dos listas cread una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

In [4]:

Serie = pd.Series(valores, index=indices)

A partir de las dos listas anteriores cread un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más información sobre este método aquí.

In [5]:

dicc = {}
for idx in range(len(indices)):
    dicc[indices[idx]] = valores[idx]

print(dicc)

{'lunes': 34, 'martes': 2, 'miercoles': 6, 'jueves': 45, 'viernes': 9, 'sabado': 12, 'domingo': 7}


Crea una Serie con el diccionario creado en el punto anterior.


In [6]:
Serie1 = pd.Series(dicc)
print(Serie1)

lunes        34
martes        2
miercoles     6
jueves       45
viernes       9
sabado       12
domingo       7
dtype: int64


¿Qué forma tiene esta última Serie?


In [7]:
Serie1.shape

(7,)

¿Qué tipo de datos tiene?


In [8]:

Serie1.dtype

dtype('int64')

¿Qué tamaño tiene?


In [9]:

Serie1.size

7

¿Cuáles son los índices de la Serie?


In [10]:

Serie1.index

Index(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado',
       'domingo'],
      dtype='object')

¿Y los values?


In [11]:

Serie1.values

array([34,  2,  6, 45,  9, 12,  7])

Extraed el valor para el índice "lunes"


In [12]:
Serie1['lunes']

34

Extraed el valor para el índice "lunes", "martes" y "miércoles".


In [13]:
Serie1[['lunes', 'martes', 'miercoles']]

lunes        34
martes        2
miercoles     6
dtype: int64

Extraed el valor para el índice "lunes" y "domingo".


In [14]:

Serie1[['lunes', 'domingo']]

lunes      34
domingo     7
dtype: int64

### 3. Es el turno de los DataFrames


Cread un array de dos dimensiones con 4 filas y 3 columnas.


In [15]:
array1 = np.random.randint(1, 7, (4, 3))
print(array1)

#Comprobamos que se ha creado correctamente y que es de dimensión 2
array1.ndim

[[6 5 4]
 [1 2 3]
 [6 2 4]
 [5 5 3]]


2

Convertid el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".


In [16]:

df1 = pd.DataFrame(array1, columns = ['España', 'Francia', 'Italia'])
print(df1)


   España  Francia  Italia
0       6        5       4
1       1        2       3
2       6        2       4
3       5        5       3


Descargad el archivo "medallas" y cargad el DataFrame con la siguiente línea de código:

In [19]:
df = pd.read_csv("datos/medallas.csv", index_col=["País"])

In [20]:
print(df)

                 Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235


📌 NOTA Para evitar problemas guardar el archivo medallas.csv a la misma altura (en la misma carpeta) que el jupyter donde estamos trabajando.

Usando el loc extraed todas las columnas de la fila de Tailandia.


In [21]:
df.loc['Tailandia', :]

Unnamed: 0      7
Oro           132
Plata         175
Bronce        278
Name: Tailandia, dtype: int64

Usando el loc extraed todas las columnas de China e Irán.


In [22]:

df.loc[['China', 'Irán'], :]

Unnamed: 0   Oro  Plata  Bronce
País                                  
China           1  1473    994     720
Irán            4   179    181     197

Usando el loc extraed solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.


In [23]:

df.loc[['China', 'Irán'],['Oro', 'Plata','Bronce']]

Oro  Plata  Bronce
País                      
China  1473    994     720
Irán    179    181     197

Usando el iloc extraed la información de la India. Devolved todas las columnas.


In [24]:
#la India corresponde con el índice 6

df.iloc[6, :]

Unnamed: 0      7
Oro           132
Plata         175
Bronce        278
Name: Tailandia, dtype: int64

Usando el iloc extraed todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.


In [25]:
df.iloc[1::2,:]

Unnamed: 0   Oro  Plata  Bronce
País                                            
Japón                     2  1032   1037     985
Irán                      4   179    181     197
India                     6   154    202     315
Indonesia                 8   112    131     240
Corea del Norte          10    91    120     235

Utilizando el código del ejercicio anterior, seleccionad unicamente las columnas "Oro", "Plata" y "Bronce".


In [32]:
df.iloc[1::2 , 0:]

Oro  Plata  Bronce
País                                
Japón            1032   1037     985
Irán              179    181     197
India             154    202     315
Indonesia         112    131     240
Corea del Norte    91    120     235

Contestad a las siguientes preguntas:
- ¿Qué país consiguió más de 200 medallas de oro?
- ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?
- ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

In [ ]:
df.loc[df.Oro> 200]
df.loc[(df['Oro']>200) & (df['Plata']>1000)]
df.loc[(df['Oro']>200) | (df['Bronce']>700)]

Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

Como vemos hay una columna que se llama Unnamed: 0 que no nos interesa. Eliminad esa columna.

In [28]:

df = df.drop("Unnamed: 0", axis=1)
df

Oro  Plata  Bronce
País                                
China            1473    994     720
Japón            1032   1037     985
Corea del Sur     745    663     827
Irán              179    181     197
Kazajistán        155    158     224
India             154    202     315
Tailandia         132    175     278
Indonesia         112    131     240
China Taipéi       99    144     276
Corea del Norte    91    120     235

Cread una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

In [29]:

df.assign(Total = df["Oro"] +df["Plata"] +df["Bronce"])

Oro  Plata  Bronce  Total
País                                       
China            1473    994     720   3187
Japón            1032   1037     985   3054
Corea del Sur     745    663     827   2235
Irán              179    181     197    557
Kazajistán        155    158     224    537
India             154    202     315    671
Tailandia         132    175     278    585
Indonesia         112    131     240    483
China Taipéi       99    144     276    519
Corea del Norte    91    120     235    446