### PAIR PROGRAMMING NUMPY 2

In [2]:
 import numpy as np

1.
Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:
El valor de la primera fila y la segunda columna.
©Extraed las filas pares (incluyendo la 0) y todas las columnas.
Extraed los valores que sean mayores que 0.5.
Extraed los valores menores que 0.2 o mayores que 0.5

In [5]:

array_miercoles = np.random.randint(4, 78, (5,3))
print(array_miercoles)

[[31  5  6]
 [39 47 71]
 [13 43 55]
 [ 4 16 23]
 [66 21 45]]


In [6]:

#El valor de la primera fila y la segunda columna.

array_miercoles[0][1]


5

In [7]:

#Extraed las filas pares (incluyendo la 0) y todas las columnas.

array_miercoles[::2][:]


array([[31,  5,  6],
       [13, 43, 55],
       [66, 21, 45]])

In [8]:

#Extraed los valores que sean mayores que 0.5.

array_miercoles[array_miercoles> 0.5]


array([31,  5,  6, 39, 47, 71, 13, 43, 55,  4, 16, 23, 66, 21, 45])

In [10]:

#Extraed los valores menores que 0.2 o mayores que 0.5

array_miercoles[(array_miercoles < 0.2) | (array_miercoles> 0.5)]

array([31,  5,  6, 39, 47, 71, 13, 43, 55,  4, 16, 23, 66, 21, 45])


2. Cread dos array de tres dimensiones:
El primero de 2 matrices, 5 filas y 3 columnas.
El segundo de 3 matrices, 2 filas y 5 columnas
Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.
Sumad los dos arrays. ¿Podéis? ¿Por qué?
Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
.reshape()
.transpose()
Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [ ]:

#El primero de 2 matrices, 5 filas y 3 columnas.

array1 = np.random.randint(1, 45, (2,5,3))

In [ ]:

#El segundo de 3 matrices, 2 filas y 5 columnas

array2 = np.random.randint(1, 45, (3,2,5))


In [15]:

#Haced un análisis exploratorio de los array creados.
#Recordad que en el ejercicio de ayer nos creamos una función para esto.

def propiedades (array):
    print(f"Este array tiene una forma {array.shape}")
    print(f"Este array tiene un tamaño {array.size}")
    print(f"Este array tiene una dimensión {array.ndim}")
    print(f"Este array contiene datos de tipo {array.dtype}")

In [16]:
propiedades(array1)
propiedades(array2)

Este array tiene una forma (2, 5, 3)
Este array tiene un tamaño 30
Este array tiene una dimensión 3
Este array contiene datos de tipo int64
Este array tiene una forma (3, 2, 5)
Este array tiene un tamaño 30
Este array tiene una dimensión 3
Este array contiene datos de tipo int64


In [17]:

#Sumad los dos arrays. ¿Podéis? ¿Por qué?

np.add(array1, array2)

# Aunque la dimensión es la misma la forma no, por eso no podemos sumarlos. 


ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

In [ ]:

#Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos 
# aprendido dos métodos:
#.reshape()
#.transpose()
#Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [20]:

array11 = np.reshape(array1, (3, 2, 5))


In [22]:
np.add(array11, array2)

array([[[56, 36, 44, 15, 76],
        [39, 53, 65, 50, 43]],

       [[85, 45, 86, 44, 70],
        [26, 37, 22, 57, 31]],

       [[30, 14, 36, 30, 38],
        [75, 46, 81, 48, 31]]])

In [25]:

array111 = np.transpose(array1, (2, 0, 1))

print(array111)

propiedades(array111)

[[[22  2 19 34 43]
  [ 8 44  4 35 37]]

 [[10 39 32 41  2]
  [ 7  8 17 31 11]]

 [[ 3 17 39  8 41]
  [ 3  7 24 16  3]]]
Este array tiene una forma (3, 2, 5)
Este array tiene un tamaño 30
Este array tiene una dimensión 3
Este array contiene datos de tipo int64


In [26]:
 propiedades(array2)

Este array tiene una forma (3, 2, 5)
Este array tiene un tamaño 30
Este array tiene una dimensión 3
Este array contiene datos de tipo int64


In [27]:
#Tras haberle cambiado la forma a los arrays ya podemos sumarlos
np.add(array111, array2)

array([[[56, 28, 60, 47, 80],
        [30, 78, 37, 46, 46]],

       [[54, 76, 75, 83, 31],
        [25, 38, 36, 44, 34]],

       [[26, 27, 58, 14, 44],
        [47, 37, 68, 53, 31]]])